fix gitci mistake

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -51,11 +51,6 @@ formatting:
     - echo "Running selene resume from checkpoint test. "
     - pwd
     - export BUILD_DIR=`pwd`
-    - |
-      if [[ $USE_CORE -eq 1 && $USE_TE -eq 1 ]]; then
-        echo "Cannot run megatron core and transformer engine together"
-        exit 1
-      fi
     - export RUN_NAME=resume_${RUN_MODEL}_tp${TP_SIZE}_pp${PP_SIZE}_${NUM_NODES}nodes
     - echo "In case of error check ${SELENE_ADLR_CI_PATH}/${CI_PIPELINE_ID}/${RUN_NAME}/results directory for result logs."
     - export TP_SIZE PP_SIZE NUM_NODES MAX_STEPS PYTORCH_IMAGE
@@ -114,6 +109,11 @@ formatting:
     - echo "$CI_MERGE_REQUEST_APPROVED"
     - pwd
     - export BUILD_DIR=`pwd`
+    - |
+      if [[ $USE_CORE -eq 1 && $USE_TE -eq 1 ]]; then
+        echo "Cannot run megatron core and transformer engine together"
+        exit 1
+      fi
     - RUN_NAME=${RUN_MODEL}_tp${TP_SIZE}_pp${PP_SIZE}_${NUM_NODES}nodes_${MAX_STEPS}steps
     - if [[ $USE_TE == 1 ]]; then RUN_NAME=${RUN_NAME}_te_enabled; fi
     - if [[ $USE_CORE == 1 ]]; then RUN_NAME=${RUN_NAME}_core_enabled; fi
