first MoE tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -51,6 +51,11 @@ formatting:
     - echo "Running selene resume from checkpoint test. "
     - pwd
     - export BUILD_DIR=`pwd`
+    - |
+      if [[ $USE_CORE -eq 1 && $USE_TE -eq 1 ]]; then
+        echo "Cannot run megatron core and transformer engine together"
+        exit 1
+      fi
     - export RUN_NAME=resume_${RUN_MODEL}_tp${TP_SIZE}_pp${PP_SIZE}_${NUM_NODES}nodes
     - echo "In case of error check ${SELENE_ADLR_CI_PATH}/${CI_PIPELINE_ID}/${RUN_NAME}/results directory for result logs."
     - export TP_SIZE PP_SIZE NUM_NODES MAX_STEPS PYTORCH_IMAGE
@@ -109,11 +114,6 @@ formatting:
     - echo "$CI_MERGE_REQUEST_APPROVED"
     - pwd
     - export BUILD_DIR=`pwd`
-    - |
-      if [[ $USE_CORE -eq 1 && $USE_TE -eq 1 ]]; then
-        echo "Cannot run megatron core and transformer engine together"
-        exit 1
-      fi
     - RUN_NAME=${RUN_MODEL}_tp${TP_SIZE}_pp${PP_SIZE}_${NUM_NODES}nodes_${MAX_STEPS}steps
     - if [[ $USE_TE == 1 ]]; then RUN_NAME=${RUN_NAME}_te_enabled; fi
     - if [[ $USE_CORE == 1 ]]; then RUN_NAME=${RUN_NAME}_core_enabled; fi
@@ -398,6 +398,41 @@ resume.checkpoint.gpt3.345m_tp1_pp2_1node:
     NUM_NODES: 1
     TIME_LIMIT: "30:00"
     TEST_LEVEL: L0
+
+# Note: Core MoE models currently will run TE by default
+train.te_core_moe_gpt3.345m_tp2_pp2_2experts_1node_50steps:
+  <<: *selene-test-launcher
+  variables:
+    <<: [*VARS]
+    RUN_MODEL: gpt3
+    USE_TE: 0
+    TP_SIZE: 2
+    PP_SIZE: 2
+    VP_SIZE: 1
+    NUM_NODES: 1
+    MAX_STEPS: 50
+    USE_CORE: 1
+    TIME_LIMIT: "20:00"
+    TEST_LEVEL: L0
+    METADATA: "te_2experts"
+    ADDITIONAL_PARAMS: "--num-experts 2"
+
+train.te_core_moe_gpt3.345m_tp2_pp2_4parallelexperts_1node_50steps:
+  <<: *selene-test-launcher
+  variables:
+    <<: [*VARS]
+    RUN_MODEL: gpt3
+    USE_TE: 0
+    TP_SIZE: 2
+    PP_SIZE: 2
+    VP_SIZE: 1
+    NUM_NODES: 1
+    MAX_STEPS: 50
+    USE_CORE: 1
+    TIME_LIMIT: "20:00"
+    TEST_LEVEL: L0
+    METADATA: "te_4parallelexperts"
+    ADDITIONAL_PARAMS: "--sequence-parallel --num-experts 4 --expert-parallel"
 
 train.bert.345m_tp4_pp1_1node_50steps:
   <<: *selene-test-launcher
