Debug
Signed-off-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -407,132 +407,132 @@ jobs:
           PAT: ${{ secrets.PAT }}
           container-image: ${{ env.container-registry }}/megatron-lm:${{ github.sha }}
 
-  cicd-parse-integration-tests:
-    runs-on: ubuntu-latest
-    needs:
-      - pre-flight
-      - cicd-wait-in-queue
-      - cicd-container-build
-      - cicd-unit-tests-latest
-    if: |
-      (
-        success()
-        || needs.pre-flight.outputs.is_ci_workload == 'true'
-        || needs.pre-flight.outputs.force_run_all == 'true'
-      )
-      && needs.pre-flight.outputs.is_merge_group == 'false'
-      && !cancelled()
-    outputs:
-      integration-tests: ${{ steps.main.outputs.integration-tests }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # cicd-parse-integration-tests:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - pre-flight
+  #     - cicd-wait-in-queue
+  #     - cicd-container-build
+  #     - cicd-unit-tests-latest
+  #   if: |
+  #     (
+  #       success()
+  #       || needs.pre-flight.outputs.is_ci_workload == 'true'
+  #       || needs.pre-flight.outputs.force_run_all == 'true'
+  #     )
+  #     && needs.pre-flight.outputs.is_merge_group == 'false'
+  #     && !cancelled()
+  #   outputs:
+  #     integration-tests: ${{ steps.main.outputs.integration-tests }}
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Get PR info
-        id: get-pr-info
-        if: startsWith(github.ref, 'refs/heads/pull-request/')
-        uses: nv-gha-runners/get-pr-info@main
+  #     - name: Get PR info
+  #       id: get-pr-info
+  #       if: startsWith(github.ref, 'refs/heads/pull-request/')
+  #       uses: nv-gha-runners/get-pr-info@main
 
-      - name: Has Run tests label
-        id: has-run-tests-label
-        env:
-          GH_TOKEN: ${{ secrets.PAT }}
-        run: |
-          PR_NUMBER=${{ fromJSON(steps.get-pr-info.outputs.pr-info || '{}').number }}
-          HAS_RUN_TESTS_LABEL=$(gh pr view $PR_NUMBER --json labels | jq '[.labels[].name] | any(. == "Run tests")') || echo "false"
-          echo "main=$HAS_RUN_TESTS_LABEL" | tee -a $GITHUB_OUTPUT
+  #     - name: Has Run tests label
+  #       id: has-run-tests-label
+  #       env:
+  #         GH_TOKEN: ${{ secrets.PAT }}
+  #       run: |
+  #         PR_NUMBER=${{ fromJSON(steps.get-pr-info.outputs.pr-info || '{}').number }}
+  #         HAS_RUN_TESTS_LABEL=$(gh pr view $PR_NUMBER --json labels | jq '[.labels[].name] | any(. == "Run tests")') || echo "false"
+  #         echo "main=$HAS_RUN_TESTS_LABEL" | tee -a $GITHUB_OUTPUT
 
-      - name: Has Run functional tests label
-        id: has-run-functional-tests-label
-        env:
-          GH_TOKEN: ${{ secrets.PAT }}
-        run: |
-          PR_NUMBER=${{ fromJSON(steps.get-pr-info.outputs.pr-info || '{}').number }}
-          HAS_RUN_FUNCTIONAL_TESTS_LABEL=$(gh pr view $PR_NUMBER --json labels | jq '[.labels[].name] | any(. == "Run functional tests")') || echo "false"
-          echo "main=$HAS_RUN_FUNCTIONAL_TESTS_LABEL" | tee -a $GITHUB_OUTPUT
+  #     - name: Has Run functional tests label
+  #       id: has-run-functional-tests-label
+  #       env:
+  #         GH_TOKEN: ${{ secrets.PAT }}
+  #       run: |
+  #         PR_NUMBER=${{ fromJSON(steps.get-pr-info.outputs.pr-info || '{}').number }}
+  #         HAS_RUN_FUNCTIONAL_TESTS_LABEL=$(gh pr view $PR_NUMBER --json labels | jq '[.labels[].name] | any(. == "Run functional tests")') || echo "false"
+  #         echo "main=$HAS_RUN_FUNCTIONAL_TESTS_LABEL" | tee -a $GITHUB_OUTPUT
 
-      - name: Parse functional tests
-        id: main
-        env:
-          HAS_RUN_TESTS_LABEL: ${{ steps.has-run-tests-label.outputs.main }}
-          HAS_RUN_FUNCTIONAL_TESTS_LABEL: ${{ steps.has-run-functional-tests-label.outputs.main }}
-        run: |
-          export PYTHONPATH=$(pwd)
+  #     - name: Parse functional tests
+  #       id: main
+  #       env:
+  #         HAS_RUN_TESTS_LABEL: ${{ steps.has-run-tests-label.outputs.main }}
+  #         HAS_RUN_FUNCTIONAL_TESTS_LABEL: ${{ steps.has-run-functional-tests-label.outputs.main }}
+  #       run: |
+  #         export PYTHONPATH=$(pwd)
 
-          if [ "$HAS_RUN_TESTS_LABEL" == "true" ]; then
-            ARGS=(
-              --scope mr-github
-              --enable-lightweight-mode
-            )
-          elif [ "$HAS_RUN_FUNCTIONAL_TESTS_LABEL" == "true" ]; then
-            ARGS=(
-              --scope mr-github
-            )
-          else
-            ARGS=(
-              --scope mr-github-slim
-            )
-          fi
+  #         if [ "$HAS_RUN_TESTS_LABEL" == "true" ]; then
+  #           ARGS=(
+  #             --scope mr-github
+  #             --enable-lightweight-mode
+  #           )
+  #         elif [ "$HAS_RUN_FUNCTIONAL_TESTS_LABEL" == "true" ]; then
+  #           ARGS=(
+  #             --scope mr-github
+  #           )
+  #         else
+  #           ARGS=(
+  #             --scope mr-github-slim
+  #           )
+  #         fi
 
-          python tests/test_utils/python_scripts/generate_jet_trigger_job.py \
-            --n-repeat 5 \
-            --time-limit 2700 \
-            --test-cases all \
-            --container-image mcore_ci_dev \
-            --container-tag latest \
-            --dependent-job functional:configure \
-            --record-checkpoints false \
-            --slurm-account gh \
-            --no-enable-warmup \
-            --environment dev \
-            --platform dgx_h100 \
-            --cluster ghci \
-            ${ARGS[@]} \
-            --output-path integration-tests.yaml
+  #         python tests/test_utils/python_scripts/generate_jet_trigger_job.py \
+  #           --n-repeat 5 \
+  #           --time-limit 2700 \
+  #           --test-cases all \
+  #           --container-image mcore_ci_dev \
+  #           --container-tag latest \
+  #           --dependent-job functional:configure \
+  #           --record-checkpoints false \
+  #           --slurm-account gh \
+  #           --no-enable-warmup \
+  #           --environment dev \
+  #           --platform dgx_h100 \
+  #           --cluster ghci \
+  #           ${ARGS[@]} \
+  #           --output-path integration-tests.yaml
 
-          cat integration-tests.yaml | \
-            yq -o json 'del(.default, .stages, .workflow) | to_entries | map({"model": .value.stage, "test_case": .key}) | sort_by(.model, .test_case)' | jq -c  > integration-tests.json
+  #         cat integration-tests.yaml | \
+  #           yq -o json 'del(.default, .stages, .workflow) | to_entries | map({"model": .value.stage, "test_case": .key}) | sort_by(.model, .test_case)' | jq -c  > integration-tests.json
 
-          echo "integration-tests=$(cat integration-tests.json)" | tee -a "$GITHUB_OUTPUT"
+  #         echo "integration-tests=$(cat integration-tests.json)" | tee -a "$GITHUB_OUTPUT"
 
-  cicd-integration-tests-latest:
-    strategy:
-      fail-fast: false
-      matrix:
-        include: ${{ fromJson(needs.cicd-parse-integration-tests.outputs.integration-tests) }}
-    needs:
-      - is-not-external-contributor
-      - pre-flight
-      - cicd-wait-in-queue
-      - cicd-parse-integration-tests
-      - cicd-unit-tests-latest
-    runs-on: ${{ needs.is-not-external-contributor.outputs.selected_runner }}
-    name: '${{ matrix.model }}/${{ matrix.test_case }} - latest'
-    env:
-      PIP_DISABLE_PIP_VERSION_CHECK: 1
-      PIP_NO_PYTHON_VERSION_WARNING: 1
-      PIP_ROOT_USER_ACTION: ignore
-    if: |
-      (
-        success()
-        || needs.pre-flight.outputs.is_ci_workload == 'true'
-        || needs.pre-flight.outputs.force_run_all == 'true'
-      )
-      && needs.pre-flight.outputs.is_merge_group == 'false'
-      && !cancelled()
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: main
-        uses: ./.github/actions
-        with:
-          test_case: ${{ matrix.test_case }}
-          model: ${{ matrix.model }}
-          tag: latest
-          timeout: ${{ matrix.timeout || 30 }}
-          is_unit_test: 'false'
-          PAT: ${{ secrets.PAT }}
-          container-image: ${{ env.container-registry }}/megatron-lm:${{ github.sha }}
+  # cicd-integration-tests-latest:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include: ${{ fromJson(needs.cicd-parse-integration-tests.outputs.integration-tests) }}
+  #   needs:
+  #     - is-not-external-contributor
+  #     - pre-flight
+  #     - cicd-wait-in-queue
+  #     - cicd-parse-integration-tests
+  #     - cicd-unit-tests-latest
+  #   runs-on: ${{ needs.is-not-external-contributor.outputs.selected_runner }}
+  #   name: '${{ matrix.model }}/${{ matrix.test_case }} - latest'
+  #   env:
+  #     PIP_DISABLE_PIP_VERSION_CHECK: 1
+  #     PIP_NO_PYTHON_VERSION_WARNING: 1
+  #     PIP_ROOT_USER_ACTION: ignore
+  #   if: |
+  #     (
+  #       success()
+  #       || needs.pre-flight.outputs.is_ci_workload == 'true'
+  #       || needs.pre-flight.outputs.force_run_all == 'true'
+  #     )
+  #     && needs.pre-flight.outputs.is_merge_group == 'false'
+  #     && !cancelled()
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: main
+  #       uses: ./.github/actions
+  #       with:
+  #         test_case: ${{ matrix.test_case }}
+  #         model: ${{ matrix.model }}
+  #         tag: latest
+  #         timeout: ${{ matrix.timeout || 30 }}
+  #         is_unit_test: 'false'
+  #         PAT: ${{ secrets.PAT }}
+  #         container-image: ${{ env.container-registry }}/megatron-lm:${{ github.sha }}
 
   Nemo_CICD_Test:
     needs:
