Debug
Signed-off-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -538,7 +538,7 @@ jobs:
     needs:
       - pre-flight
       - cicd-unit-tests-latest
-      - cicd-integration-tests-latest
+      # - cicd-integration-tests-latest
     if: |
       (
         needs.pre-flight.outputs.docs_only == 'true'
@@ -576,100 +576,100 @@ jobs:
               exit 1
           fi
 
-  Coverage_Fake:
-    runs-on: ubuntu-latest
-    needs: [Nemo_CICD_Test, pre-flight]
-    if: |
-      (
-        needs.pre-flight.outputs.docs_only == 'true'
-        || needs.pre-flight.outputs.is_deployment_workflow == 'true'
-        || github.event == 'merge_group'
-      )
-      && needs.pre-flight.outputs.is_ci_workload == 'false'
-      && !cancelled()
-      && github.repository == 'NVIDIA/Megatron-LM'
-    steps:
-      - name: Generate fake coverage report
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.PAT }}
-          script: |
-            await github.rest.repos.createCommitStatus({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              sha: context.sha,
-              state: 'success',
-              description: 'No code changes - coverage check skipped',
-              context: 'codecov/patch'
-            });
+  # Coverage_Fake:
+  #   runs-on: ubuntu-latest
+  #   needs: [Nemo_CICD_Test, pre-flight]
+  #   if: |
+  #     (
+  #       needs.pre-flight.outputs.docs_only == 'true'
+  #       || needs.pre-flight.outputs.is_deployment_workflow == 'true'
+  #       || github.event == 'merge_group'
+  #     )
+  #     && needs.pre-flight.outputs.is_ci_workload == 'false'
+  #     && !cancelled()
+  #     && github.repository == 'NVIDIA/Megatron-LM'
+  #   steps:
+  #     - name: Generate fake coverage report
+  #       uses: actions/github-script@v6
+  #       with:
+  #         github-token: ${{ secrets.PAT }}
+  #         script: |
+  #           await github.rest.repos.createCommitStatus({
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             sha: context.sha,
+  #             state: 'success',
+  #             description: 'No code changes - coverage check skipped',
+  #             context: 'codecov/patch'
+  #           });
 
-  Coverage:
-    runs-on: ubuntu-latest
-    needs: [Nemo_CICD_Test]
-    if: |
-      (
-        (needs.pre-flight.outputs.is_ci_workload == 'true' && !failure())
-        || success()
-      )
-      && !cancelled()
-      && github.repository == 'NVIDIA/Megatron-LM'
-    strategy:
-      matrix:
-        flag: [unit-test]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # Coverage:
+  #   runs-on: ubuntu-latest
+  #   needs: [Nemo_CICD_Test]
+  #   if: |
+  #     (
+  #       (needs.pre-flight.outputs.is_ci_workload == 'true' && !failure())
+  #       || success()
+  #     )
+  #     && !cancelled()
+  #     && github.repository == 'NVIDIA/Megatron-LM'
+  #   strategy:
+  #     matrix:
+  #       flag: [unit-test]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Download coverage reports of current branch
-        uses: actions/download-artifact@v4
-        with:
-          pattern: coverage-${{ matrix.flag }}-*
+  #     - name: Download coverage reports of current branch
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: coverage-${{ matrix.flag }}-*
 
-      - name: List coverage files
-        run: find . -type f -name "*.xml" -o -name "*.lcov"
+  #     - name: List coverage files
+  #       run: find . -type f -name "*.xml" -o -name "*.lcov"
 
-      - name: Get total coverage of current branch
-        shell: bash -x -e -u -o pipefail {0}
-        if: always()
-        run: |
-          pip install coverage
+  #     - name: Get total coverage of current branch
+  #       shell: bash -x -e -u -o pipefail {0}
+  #       if: always()
+  #       run: |
+  #         pip install coverage
 
-          ls -al .
-          ls -al coverage-*/
-          coverage combine --keep $(ls coverage-*/.coverage)
-          coverage report -i
-          rm -rf coverage-*
-          ls -al
+  #         ls -al .
+  #         ls -al coverage-*/
+  #         coverage combine --keep $(ls coverage-*/.coverage)
+  #         coverage report -i
+  #         rm -rf coverage-*
+  #         ls -al
 
-      - name: Upload coverage reports to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          verbose: true
-          flags: ${{ matrix.flag }}
+  #     - name: Upload coverage reports to Codecov
+  #       uses: codecov/codecov-action@v5
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         verbose: true
+  #         flags: ${{ matrix.flag }}
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-${{ matrix.flag }}-aggregated
-          path: |
-            .coverage
-          include-hidden-files: true
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: coverage-${{ matrix.flag }}-aggregated
+  #         path: |
+  #           .coverage
+  #         include-hidden-files: true
 
-  cleanup-taint-node:
-    runs-on: ${{ needs.is-not-external-contributor.outputs.selected_runner }}
-    needs:
-      - is-not-external-contributor
-      - cicd-container-build
-      - cicd-unit-tests-latest
-      - cicd-integration-tests-latest
-      - Coverage
-      - Coverage_Fake
-    if: |
-      always()
-      && !cancelled()
-      && contains(needs.is-not-external-contributor.outputs.selected_runner, 'ephemeral')
-    steps:
-      - name: Taint node for cleanup
-        shell: bash
-        run: taint-node.sh
+  # cleanup-taint-node:
+  #   runs-on: ${{ needs.is-not-external-contributor.outputs.selected_runner }}
+  #   needs:
+  #     - is-not-external-contributor
+  #     - cicd-container-build
+  #     - cicd-unit-tests-latest
+  #     # - cicd-integration-tests-latest
+  #     - Coverage
+  #     - Coverage_Fake
+  #   if: |
+  #     always()
+  #     && !cancelled()
+  #     && contains(needs.is-not-external-contributor.outputs.selected_runner, 'ephemeral')
+  #   steps:
+  #     - name: Taint node for cleanup
+  #       shell: bash
+  #       run: taint-node.sh
